name: flutter_task
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  provider: ^6.1.2
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.0


flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    
  # fonts:
  #   - family: Arial
  #     fonts:
  #       - asset: assets/fonts/Arial.ttf
  #       - asset: assets/fonts/Arial Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Arial Italic.ttf
  #       - asset: assets/fonts/Arial Bold Italic.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
